## Building ML Model to prediction Teams position based on season's performance

Trying to build an ML model to predict the position of teams in the EPL based on the 2021/2022 Season. 

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('EPL Standings 2000-2022.csv')

In [3]:
df.head()

Season  Pos               Team  Pld   W   D   L  GF  GA  GD  Pts  \
0  2000-01    1  Manchester United   38  24   8   6  79  31  48   80   
1  2000-01    2            Arsenal   38  20  10   8  63  38  25   70   
2  2000-01    3          Liverpool   38  20   9   9  71  39  32   69   
3  2000-01    4       Leeds United   38  20   8  10  64  43  21   68   
4  2000-01    5       Ipswich Town   38  20   6  12  57  42  15   66   

                         Qualification or relegation  
0  Qualification for the Champions League first g...  
1  Qualification for the Champions League first g...  
2  Qualification for the Champions League third q...  
3      Qualification for the UEFA Cup first round[a]  
4      Qualification for the UEFA Cup first round[a]

In [4]:
df[df.Season == '2021-22']

Season  Pos                     Team  Pld   W   D   L  GF  GA  GD  Pts  \
420  2021-22    1          Manchester City   38  29   6   3  99  26  73   93   
421  2021-22    2                Liverpool   38  28   8   2  94  26  68   92   
422  2021-22    3                  Chelsea   38  21  11   6  76  33  43   74   
423  2021-22    4        Tottenham Hotspur   38  22   5  11  69  40  29   71   
424  2021-22    5                  Arsenal   38  22   3  13  61  48  13   69   
425  2021-22    6        Manchester United   38  16  10  12  57  57   0   58   
426  2021-22    7          West Ham United   38  16   8  14  60  51   9   56   
427  2021-22    8           Leicester City   38  14  10  14  62  59   3   52   
428  2021-22    9   Brighton & Hove Albion   38  12  15  11  42  44  -2   51   
429  2021-22   10  Wolverhampton Wanderers   38  15   6  17  38  43  -5   51   
430  2021-22   11         Newcastle United   38  13  10  15  44  62 -18   49   
431  2021-22   12           Crystal Palace   38  11  15  12  50  46   4   48   
432  2021-22   13                Brentford   38  13   7  18  48  56  -8   46   
433  2021-22   14              Aston Villa   38  13   6  19  52  54  -2   45   
434  2021-22   15              Southampton   38   9  13  16  43  67 -24   40   
435  2021-22   16                  Everton   38  11   6  21  43  66 -23   39   
436  2021-22   17             Leeds United   38   9  11  18  42  79 -37   38   
437  2021-22   18                  Burnley   38   7  14  17  34  53 -19   35   
438  2021-22   19                  Watford   38   6   5  27  34  77 -43   23   
439  2021-22   20             Norwich City   38   5   7  26  23  84 -61   22   

                           Qualification or relegation  
420  Qualification for the Champions League group s...  
421  Qualification for the Champions League group s...  
422  Qualification for the Champions League group s...  
423  Qualification for the Champions League group s...  
424  Qualification for the Europa League group stag...  
425  Qualification for the Europa League group stag...  
426  Qualification for the Europa Conference League...  
427                                     Not Applicable  
428                                     Not Applicable  
429                                     Not Applicable  
430                                     Not Applicable  
431                                     Not Applicable  
432                                     Not Applicable  
433                                     Not Applicable  
434                                     Not Applicable  
435                                     Not Applicable  
436                                     Not Applicable  
437                 Relegation to the EFL Championship  
438                 Relegation to the EFL Championship  
439                 Relegation to the EFL Championship

In [5]:
data2022 = df[df.Season == '2021-22']

In [8]:
data2022.drop(['Season','Qualification or relegation','Team','Pld'],axis = 1,inplace = True)

C:\Users\Cypher\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [9]:
data2022

Pos   W   D   L  GF  GA  GD  Pts
420    1  29   6   3  99  26  73   93
421    2  28   8   2  94  26  68   92
422    3  21  11   6  76  33  43   74
423    4  22   5  11  69  40  29   71
424    5  22   3  13  61  48  13   69
425    6  16  10  12  57  57   0   58
426    7  16   8  14  60  51   9   56
427    8  14  10  14  62  59   3   52
428    9  12  15  11  42  44  -2   51
429   10  15   6  17  38  43  -5   51
430   11  13  10  15  44  62 -18   49
431   12  11  15  12  50  46   4   48
432   13  13   7  18  48  56  -8   46
433   14  13   6  19  52  54  -2   45
434   15   9  13  16  43  67 -24   40
435   16  11   6  21  43  66 -23   39
436   17   9  11  18  42  79 -37   38
437   18   7  14  17  34  53 -19   35
438   19   6   5  27  34  77 -43   23
439   20   5   7  26  23  84 -61   22

In [77]:
y = data2022.Pos.values.reshape(-1,1)
X = data2022.drop(['Pos','D','GD'],axis = 1).values

In [78]:
X

array([[29,  3, 99, 26, 93],
       [28,  2, 94, 26, 92],
       [21,  6, 76, 33, 74],
       [22, 11, 69, 40, 71],
       [22, 13, 61, 48, 69],
       [16, 12, 57, 57, 58],
       [16, 14, 60, 51, 56],
       [14, 14, 62, 59, 52],
       [12, 11, 42, 44, 51],
       [15, 17, 38, 43, 51],
       [13, 15, 44, 62, 49],
       [11, 12, 50, 46, 48],
       [13, 18, 48, 56, 46],
       [13, 19, 52, 54, 45],
       [ 9, 16, 43, 67, 40],
       [11, 21, 43, 66, 39],
       [ 9, 18, 42, 79, 38],
       [ 7, 17, 34, 53, 35],
       [ 6, 27, 34, 77, 23],
       [ 5, 26, 23, 84, 22]], dtype=int64)

In [79]:
#building baseline model
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()


In [80]:
model1.fit(X,y)

LinearRegression()

In [81]:
model1.score(X,y)

0.9143959981911909

In [82]:
model1.predict(X)

array([[-0.76414645],
       [-0.81385342],
       [ 4.4161049 ],
       [ 5.04746709],
       [ 5.11660299],
       [ 8.64707567],
       [ 9.76781196],
       [11.2524342 ],
       [10.22962619],
       [10.15504072],
       [10.97113991],
       [11.93330267],
       [12.56757072],
       [13.30170103],
       [14.13321293],
       [14.69062562],
       [14.67016245],
       [15.52779772],
       [19.88185139],
       [19.26847171]])

In [83]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [84]:
X_scaled = scaler.fit_transform(X)

In [85]:
model2 = LinearRegression()

In [86]:
model2.fit(X_scaled,y)

LinearRegression()

In [87]:
model2.score(X_scaled,y)

0.9143959981911909

In [88]:
model2.predict(X_scaled)

array([[-0.76414645],
       [-0.81385342],
       [ 4.4161049 ],
       [ 5.04746709],
       [ 5.11660299],
       [ 8.64707567],
       [ 9.76781196],
       [11.2524342 ],
       [10.22962619],
       [10.15504072],
       [10.97113991],
       [11.93330267],
       [12.56757072],
       [13.30170103],
       [14.13321293],
       [14.69062562],
       [14.67016245],
       [15.52779772],
       [19.88185139],
       [19.26847171]])

In [89]:
from sklearn.ensemble import RandomForestRegressor

In [90]:
model3 = RandomForestRegressor()

In [91]:
model3.fit(X_scaled,y)

C:\Users\Cypher\AppData\Local\Temp/ipykernel_8384/3506007955.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(X_scaled,y)


RandomForestRegressor()

In [92]:
model3.score(X_scaled,y)

0.9944601503759398

In [93]:
model3.predict(X_scaled)

array([ 1.41,  1.87,  3.12,  4.15,  5.12,  6.55,  7.01,  8.46,  9.41,
       10.05, 11.66, 11.63, 13.1 , 13.47, 15.43, 15.62, 16.42, 17.23,
       18.72, 19.25])

In [94]:
from sklearn.linear_model import Lasso

In [95]:
model4 = Lasso()
model4.fit(X_scaled,y)

Lasso()

In [96]:
model4.score(X_scaled,y)

0.878704256281137

In [97]:
model4.predict(X_scaled)

array([ 0.86483389,  1.1033281 ,  5.39622389,  6.11170652,  6.58869495,
        9.21213126,  9.68911968, 10.64309653, 10.88159074, 10.88159074,
       11.35857916, 11.59707337, 12.07406179, 12.312556  , 13.50502705,
       13.74352126, 13.98201548, 14.69749811, 17.55942864, 17.79792285])

In [98]:
from catboost import CatBoostRegressor

In [99]:
ctb = CatBoostRegressor()

In [100]:
ctb.fit(X_scaled,y,silent=True)

In [101]:
ctb.predict(X_scaled)

array([ 1.02255396,  2.00794005,  3.00559643,  3.96368005,  5.02662549,
        6.01438108,  6.97364612,  8.00680735,  9.01655852, 10.00325688,
       10.98240212, 11.97878973, 13.03080108, 13.99360296, 15.01945954,
       15.99523053, 16.99237744, 17.98955971, 19.00294519, 19.98139352])

In [102]:
df

Season  Pos               Team  Pld   W   D   L  GF  GA  GD  Pts  \
0    2000-01    1  Manchester United   38  24   8   6  79  31  48   80   
1    2000-01    2            Arsenal   38  20  10   8  63  38  25   70   
2    2000-01    3          Liverpool   38  20   9   9  71  39  32   69   
3    2000-01    4       Leeds United   38  20   8  10  64  43  21   68   
4    2000-01    5       Ipswich Town   38  20   6  12  57  42  15   66   
..       ...  ...                ...  ...  ..  ..  ..  ..  ..  ..  ...   
435  2021-22   16            Everton   38  11   6  21  43  66 -23   39   
436  2021-22   17       Leeds United   38   9  11  18  42  79 -37   38   
437  2021-22   18            Burnley   38   7  14  17  34  53 -19   35   
438  2021-22   19            Watford   38   6   5  27  34  77 -43   23   
439  2021-22   20       Norwich City   38   5   7  26  23  84 -61   22   

                           Qualification or relegation  
0    Qualification for the Champions League first g...  
1    Qualification for the Champions League first g...  
2    Qualification for the Champions League third q...  
3        Qualification for the UEFA Cup first round[a]  
4        Qualification for the UEFA Cup first round[a]  
..                                                 ...  
435                                     Not Applicable  
436                                     Not Applicable  
437                 Relegation to the EFL Championship  
438                 Relegation to the EFL Championship  
439                 Relegation to the EFL Championship  

[440 rows x 12 columns]

In [108]:
#Test Sets
Testset1 = df[df.Season == '2020-21']
Testset1

Season  Pos                     Team  Pld   W   D   L  GF  GA  GD  Pts  \
400  2020-21    1          Manchester City   38  27   5   6  83  32  51   86   
401  2020-21    2        Manchester United   38  21  11   6  73  44  29   74   
402  2020-21    3                Liverpool   38  20   9   9  68  42  26   69   
403  2020-21    4                  Chelsea   38  19  10   9  58  36  22   67   
404  2020-21    5           Leicester City   38  20   6  12  68  50  18   66   
405  2020-21    6          West Ham United   38  19   8  11  62  47  15   65   
406  2020-21    7        Tottenham Hotspur   38  18   8  12  68  45  23   62   
407  2020-21    8                  Arsenal   38  18   7  13  55  39  16   61   
408  2020-21    9             Leeds United   38  18   5  15  62  54   8   59   
409  2020-21   10                  Everton   38  17   8  13  47  48  -1   59   
410  2020-21   11              Aston Villa   38  16   7  15  55  46   9   55   
411  2020-21   12         Newcastle United   38  12   9  17  46  62 -16   45   
412  2020-21   13  Wolverhampton Wanderers   38  12   9  17  36  52 -16   45   
413  2020-21   14           Crystal Palace   38  12   8  18  41  66 -25   44   
414  2020-21   15              Southampton   38  12   7  19  47  68 -21   43   
415  2020-21   16   Brighton & Hove Albion   38   9  14  15  40  46  -6   41   
416  2020-21   17                  Burnley   38  10   9  19  33  55 -22   39   
417  2020-21   18                   Fulham   38   5  13  20  27  53 -26   28   
418  2020-21   19     West Bromwich Albion   38   5  11  22  35  76 -41   26   
419  2020-21   20         Sheffield United   38   7   2  29  20  63 -43   23   

                           Qualification or relegation  
400  Qualification for the Champions League group s...  
401  Qualification for the Champions League group s...  
402  Qualification for the Champions League group s...  
403  Qualification for the Champions League group s...  
404  Qualification for the Europa League group stag...  
405  Qualification for the Europa League group stag...  
406  Qualification for the Europa Conference League...  
407                                     Not Applicable  
408                                     Not Applicable  
409                                     Not Applicable  
410                                     Not Applicable  
411                                     Not Applicable  
412                                     Not Applicable  
413                                     Not Applicable  
414                                     Not Applicable  
415                                     Not Applicable  
416                                     Not Applicable  
417                 Relegation to the EFL Championship  
418                 Relegation to the EFL Championship  
419                 Relegation to the EFL Championship

In [109]:
y_test1 = Testset1.Pos.values.reshape(-1,1)
X_test1 = Testset1.drop('Pos',axis = 1)
X_test1.drop(['Season','Qualification or relegation','Team','Pld','D','GD'],axis = 1,inplace = True)

In [110]:
X_test1_scaled = scaler.fit_transform(X_test1)

In [111]:
ctbpred2021 = ctb.predict(X_test1_scaled).reshape(-1)
ctbpred2021

array([ 1.6453892 ,  3.21113748,  3.46018535,  3.92048883,  5.13614911,
        4.93442376,  4.87895384,  5.69208077,  7.20119056,  6.97822596,
        7.64414618, 14.72240993, 15.74630402, 15.67403076, 15.06694292,
       14.14637459, 17.42924142, 18.16499791, 19.74231296, 19.04193864])

In [112]:
linearpred2021 = model2.predict(X_test1_scaled).reshape(-1)
linearpred2021

array([-0.52154693,  3.35578493,  5.17891544,  5.27104929,  6.37950339,
        6.29631272,  8.16802137,  7.61805901,  8.81759979,  7.54893965,
       10.05700241, 13.17676222, 12.52085447, 13.10653611, 14.05024329,
       14.60186679, 14.78552052, 18.95228621, 20.05995289, 20.57633643])

In [113]:
Rfpred2021 = model3.predict(X_test1_scaled).reshape(-1)
Rfpred2021

array([ 1.76,  3.62,  3.65,  4.17,  4.55,  4.72,  5.55,  5.87,  6.67,
        7.43,  7.26, 14.04, 14.54, 15.11, 14.74, 15.53, 16.59, 18.04,
       19.  , 18.81])

In [114]:
results = pd.DataFrame({'LinearPred': linearpred2021,'CatboostPred':ctbpred2021,'RfPred':Rfpred2021})

In [115]:
results

LinearPred  CatboostPred  RfPred
0    -0.521547      1.645389    1.76
1     3.355785      3.211137    3.62
2     5.178915      3.460185    3.65
3     5.271049      3.920489    4.17
4     6.379503      5.136149    4.55
5     6.296313      4.934424    4.72
6     8.168021      4.878954    5.55
7     7.618059      5.692081    5.87
8     8.817600      7.201191    6.67
9     7.548940      6.978226    7.43
10   10.057002      7.644146    7.26
11   13.176762     14.722410   14.04
12   12.520854     15.746304   14.54
13   13.106536     15.674031   15.11
14   14.050243     15.066943   14.74
15   14.601867     14.146375   15.53
16   14.785521     17.429241   16.59
17   18.952286     18.164998   18.04
18   20.059953     19.742313   19.00
19   20.576336     19.041939   18.81

In [118]:
results['Linearappox'] = results.LinearPred.apply(lambda x: 1 if x<1 else 20 if x>20 else round(x))

In [119]:
results

LinearPred  CatboostPred  RfPred  Linearappox
0    -0.521547      1.645389    1.76            1
1     3.355785      3.211137    3.62            3
2     5.178915      3.460185    3.65            5
3     5.271049      3.920489    4.17            5
4     6.379503      5.136149    4.55            6
5     6.296313      4.934424    4.72            6
6     8.168021      4.878954    5.55            8
7     7.618059      5.692081    5.87            8
8     8.817600      7.201191    6.67            9
9     7.548940      6.978226    7.43            8
10   10.057002      7.644146    7.26           10
11   13.176762     14.722410   14.04           13
12   12.520854     15.746304   14.54           13
13   13.106536     15.674031   15.11           13
14   14.050243     15.066943   14.74           14
15   14.601867     14.146375   15.53           15
16   14.785521     17.429241   16.59           15
17   18.952286     18.164998   18.04           19
18   20.059953     19.742313   19.00           20
19   20.576336     19.041939   18.81           20

In [120]:
results['Catboostapprox'] = results.CatboostPred.apply(lambda x: 1 if x<1 else round(x))
results

LinearPred  CatboostPred  RfPred  Linearappox  Catboostapprox
0    -0.521547      1.645389    1.76            1               2
1     3.355785      3.211137    3.62            3               3
2     5.178915      3.460185    3.65            5               3
3     5.271049      3.920489    4.17            5               4
4     6.379503      5.136149    4.55            6               5
5     6.296313      4.934424    4.72            6               5
6     8.168021      4.878954    5.55            8               5
7     7.618059      5.692081    5.87            8               6
8     8.817600      7.201191    6.67            9               7
9     7.548940      6.978226    7.43            8               7
10   10.057002      7.644146    7.26           10               8
11   13.176762     14.722410   14.04           13              15
12   12.520854     15.746304   14.54           13              16
13   13.106536     15.674031   15.11           13              16
14   14.050243     15.066943   14.74           14              15
15   14.601867     14.146375   15.53           15              14
16   14.785521     17.429241   16.59           15              17
17   18.952286     18.164998   18.04           19              18
18   20.059953     19.742313   19.00           20              20
19   20.576336     19.041939   18.81           20              19

In [121]:
results['Rfapprox'] = results.RfPred.apply(lambda x: 1 if x<1 else 20 if x>20 else round(x))
results

LinearPred  CatboostPred  RfPred  Linearappox  Catboostapprox  Rfapprox
0    -0.521547      1.645389    1.76            1               2         2
1     3.355785      3.211137    3.62            3               3         4
2     5.178915      3.460185    3.65            5               3         4
3     5.271049      3.920489    4.17            5               4         4
4     6.379503      5.136149    4.55            6               5         5
5     6.296313      4.934424    4.72            6               5         5
6     8.168021      4.878954    5.55            8               5         6
7     7.618059      5.692081    5.87            8               6         6
8     8.817600      7.201191    6.67            9               7         7
9     7.548940      6.978226    7.43            8               7         7
10   10.057002      7.644146    7.26           10               8         7
11   13.176762     14.722410   14.04           13              15        14
12   12.520854     15.746304   14.54           13              16        15
13   13.106536     15.674031   15.11           13              16        15
14   14.050243     15.066943   14.74           14              15        15
15   14.601867     14.146375   15.53           15              14        16
16   14.785521     17.429241   16.59           15              17        17
17   18.952286     18.164998   18.04           19              18        18
18   20.059953     19.742313   19.00           20              20        19
19   20.576336     19.041939   18.81           20              19        19

In [127]:
data = pd.concat([Testset1.reset_index(),results.reset_index()],axis=1)

In [128]:
data.drop(['index','Qualification or relegation','GF','GA','W','L','D','Pld'],axis=1,inplace = True)

In [129]:
data.to_csv('EPL 2021 prediction.csv',index=False)

Season  Pos             Team  Pld   W   D  L  GF  GA  GD  Pts  \
60   2003-04    1          Arsenal   38  26  12  0  73  26  47   90   
220  2011-12    1  Manchester City   38  28   5  5  93  29  64   89   
300  2015-16    1   Leicester City   38  23  12  3  68  36  32   81   

                           Qualification or relegation  
60   Qualification for the Champions League group s...  
220  Qualification for the Champions League group s...  
300  Qualification for the Champions League group s...

array([ 7.03120146,  6.77571256, 18.31494277])

array([ 4.70931151, 10.74335252, 16.04733597])

array([ 6.41,  5.15, 17.99])